#!/usr/bin/env bash
# Bash script displaying the information about subdomains
function audit_subdomain {
    local domain="$1"
    local subdomain="$2"
    local result
    result=$(dig +short "$subdomain"."$domain")

    if [[ -n "$result" ]]; then
	    local record_type
	    record_type=$(dig "$subdomain"."$domain" | awk '/^;; ANSWER SECTION:$/ { getline; print $4 }')
	    echo "The subdomain $subdomain is a $record_type record and points to $result"
    fi
}

domain="$1"
subdomain="${2:-all}"

if [[ $subdomain == "all" ]]; then
    audit_subdomain "$domain" "www"
    audit_subdomain "$domain" "lb-01"
    audit_subdomain "$domain" "web-01"
    audit_subdomain "$domain" "web-02"
else
    audit_subdomain "$domain" "$subdomain"
fi

