#!/usr/bin/env bash
# copying a file from client to sever
if [ $# -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else 
	path_file=$1
	ip=$2
	username=$3
	path_key=$4
	scp -o StrictHostKeyChecking=no -i "$path_key" "$path_file" "$username"@"$ip":~/
fi
