#!/usr/bin/env bash
# installing nginx on web server
sudo get-apt -y upadate
sudo get-apt -y install nginx
sudo ufw allow "Nginx HTTP"
echo "Hello World!" > /var/www/html/index.html
sudo service nginx restart
