#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
sudo echo -e "Ceci n'est pas une page" >> /var/www/html/error_404.html
sudo sed -i '37i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
