#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
sudo sed -i 's|#error_page 404 /404.html;|error_page 404 /404.html;\n\tlocation = /404.html {\n\t\tinternal;\n\t\treturn 404 "Ceci n'\''est pas une page";\n\t}|\n' /etc/nginx/sites-available/default
sudo service nginx restart
