#!/usr/bin/env bash
# configuring two servers
sudo apt-get -y update
sudo apt-get -y install nginx
sud ufw allow 'Nginx HTTP'
echo "Hello world!" > /var/www/html/index.html
sed i "37i\ \n\tlocation /redirect_me {\n\treturn 301 https://youtu.be/dQw4w9WgXcQ;\n\t}\n" "/etc/nginx/sites-available/default"
echo "Ceci n'est pas une page" > "/usr/share/nginx/html//404error.html"
sed i "37i\ \n\terror_page 404 /404error.html;\n\tlocation = /404error.html {\n\troot /usr/share/nginx/html;\n\tinternal;\n\t}\n" "/etc/nginx/sites-available/default"
sed i "37i\n\tadd_header X-served-By $hostname;\n" "/etc/nginx/sites-available/default"
sudo service nginx restart
