#!/usr/bin/env bash
# intalling haproxy
sudo apt update
sudo apt install -y haproxy

sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOT
frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    mode http
    balance roundrobin
    server 80820-web-01 174.129.68.202:80 check
    server 80820-web-02 100.26.53.81:80 check
EOT

sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

sudo service haproxy restart

