#!/usr/bin/env bash
# intalling haproxyi
sudo apt-get -y software-properties-common
sudo apt-get -y ppa:vbernat/haproxy
sudo apt-get update
sudo apt-get install -y haproxy
echo "ENABLED=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg
printf %s "global
	log 127.0.0.1 local0 notice
	user haproxy
	group haproxy
defaults
	log global
	mode http
	retries 3
	timeout connect 5000
	timeout client 10000
	timeout server 10000
listen hbnb
	bind 0.0.0.0:80
	mode http
	stats enable
	balance roundrobin
	server 80820-web-01 174.129.68.202:80 check
	server 80820-web-02 100.26.53.81:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart

