#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
HR=0
while [ "$HR" -le 12 ]
do
        echo "Hour: $HR"
	HR=$((HR + 1))
	MIN=1
	while [ "$MIN" -le 60 ]
	do
		echo "$MIN"
		MIN=$((MIN + 1))
	done
done
