#!/usr/bin/env bash
#checking for a file
FILENAME="school"
if [ -e "$FILENAME" ]; then 
	echo "$FILENAME file exists"
	if [ -s "$FILENAME" ]; then
		echo "$FILENAME file is not empty"
	else
		echo "$FILENAME file is empty"
	fi
	if [ -f "$FILENAME" ]; then 
		echo "$FILENAME is a regular file"
	fi
else
	echo "$FILENAME file does not exist"
fi
