#!/usr/bin/env bash
#Bash script that configures Nginx
if ! command -v nginx > /dev/null 2>&1; then apt-get update; apt-get install -y nginx; fi
sed -i 's/^user .*/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/^listen .*/listen \*:8080;/g' /etc/nginx/sites-available/default
service nginx restart
